language: scala
script:
  - if [ $KIND == main ]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION package packageDoc testing/test scalajs-test/test scalajs-compiler/test reversi/packageJS reversi/optimizeJS; fi
  - if [[ "$KIND" == "main" && "$PUBLISH_ENABLED" == "true" ]]; then sbt "${SBT_SETUP}" 'set sources in (exampleTesting, Test, ScalaJSKeys.scalaJSEnvironment) := Seq((ScalaJSKeys.preoptimizeJS in (exampleTesting, Test)).value)' ++$TRAVIS_SCALA_VERSION testing/test 'set sources in (exampleTesting, Test, ScalaJSKeys.scalaJSEnvironment) := Seq((ScalaJSKeys.optimizeJS in (exampleTesting, Test)).value)' ++$TRAVIS_SCALA_VERSION testing/test; fi
  - if [ $KIND == main ]; then sh checksizes.sh $TRAVIS_SCALA_VERSION; fi
  - if [ $KIND == main ]; then sh check-partest-coverage.sh $TRAVIS_SCALA_VERSION; fi
  - if [ $KIND == sbtplugin ]; then sbt "${SBT_SETUP}" scalajs-sbt-plugin/package; fi
after_success:
  - if [[ "${PUBLISH_ENABLED}" == "true" && "${TRAVIS_PULL_REQUEST}" == "false" && "${KIND}" == "main" && "${PUBLISH_USER}" != "" && "${PUBLISH_PASS}" != "" ]]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION publish; fi
  - if [[ "${PUBLISH_ENABLED}" == "true" && "${TRAVIS_PULL_REQUEST}" == "false" && "${KIND}" == "sbtplugin" && "${PUBLISH_USER}" != "" && "${PUBLISH_PASS}" != "" ]]; then sbt "${SBT_SETUP}" scalajs-sbt-plugin/publish; fi
env:
  global:
    - secure: "gIReAZ60hLtbYTlnNUM508LhhznImVPRO5fHQ/9SY7mqA/ql3EVJ65M43GxzvKjNkZ7thKj1ygYklCQaqXwdszR8xRRM7MNQIUImZhsjXJ0xqorpQf2fmo2sD54Gx/caAI4kx0x/ULm9ZA5QK6hprl8aVqb1o5bYAxfZdx719pE="
    - secure: "CiwH9VZ0Wl/fGsL6XUbXv92TWr+EnX94ICX2cbwwkvPDxmTrdWf8BZOq7JSrfITYvvW3l5U8YWLjCMpa/Cr2C2BD1QPvNXDoeL9cZXA0I2yquQNEfh12Zg5c5bHRtO+CeRHjq06jjEqojqTzp5MK10YXnfzzQFiZ1lt7c/rwmkU="
matrix:
  include:
    - jdk: openjdk6
      scala: 2.10.2
      env:
        - KIND=main
        - PUBLISH_ENABLED=true
    - jdk: openjdk6
      scala: 2.10.2
      env:
        - KIND=sbtplugin
        - PUBLISH_ENABLED=true
    - jdk: openjdk6
      scala: 2.10.3
      env:
        - KIND=main
    - jdk: openjdk6
      scala: 2.10.4-RC3
      env:
        - KIND=main
    - jdk: openjdk6
      scala: 2.11.0-M7
      env:
        - KIND=main
        - PUBLISH_ENABLED=true
    - jdk: openjdk6
      scala: 2.11.0-M7
      env:
        - KIND=main
        - SBT_SETUP='set scalacOptions in ScalaJSBuild.test += "-Xexperimental"'
    - jdk: openjdk6
      scala: 2.11.0-M8
      env:
        - KIND=main
        - PUBLISH_ENABLED=true
    - jdk: openjdk6
      scala: 2.11.0-M8
      env:
        - KIND=main
        - SBT_SETUP='set scalacOptions in ScalaJSBuild.test += "-Xexperimental"'
    - jdk: oraclejdk7
      scala: 2.10.2
      env:
        - KIND=main
    - jdk: oraclejdk7
      scala: 2.10.3
      env:
        - KIND=main
    - jdk: oraclejdk7
      scala: 2.10.4-RC3
      env:
        - KIND=main
    - jdk: oraclejdk7
      scala: 2.11.0-M7
      env:
        - KIND=main
    - jdk: oraclejdk7
      scala: 2.11.0-M8
      env:
        - KIND=main
