language: scala
script:
  - if [ $KIND == main ]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION package packageDoc; fi
  - if [ $KIND == main ]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION testing/test testing/fastOptStage::test testing/fullOptStage::test; fi
  - if [ $KIND == main ]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION scalajs-test/test scalajs-test/fastOptStage::test scalajs-test/fullOptStage::test; fi
  - |
    if [ $KIND == main ]; then
      # Bug in Phantom.js prevents us from running IntTest - #593
      sbt "${SBT_SETUP}" \
        'set ScalaJSKeys.postLinkJSEnv in ScalaJSBuild.test := new scala.scalajs.sbtplugin.env.phantomjs.PhantomJSEnv' \
        'set definedTests.in(ScalaJSBuild.test, Test) ~= (_.filter(_.name != "scala.scalajs.test.compiler.IntTest"))' \
        ++$TRAVIS_SCALA_VERSION \
        scalajs-test/packageStage::test scalajs-test/fastOptStage::test scalajs-test/fullOptStage::test scalajs-test/clean
    fi
  - |
    if [ $KIND == main ]; then
      sbt "${SBT_SETUP}" \
        'set scalacOptions in ScalaJSBuild.test += "-Xexperimental"' ++$TRAVIS_SCALA_VERSION \
        scalajs-test/test scalajs-test/fastOptStage::test scalajs-test/fullOptStage::test
    fi
  - if [ $KIND == main ]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION scalajs-compiler/test reversi/packageJS reversi/fullOptJS; fi
  - if [ $KIND == main ]; then sh checksizes.sh $TRAVIS_SCALA_VERSION; fi
  - if [ $KIND == main ]; then sh check-partest-coverage.sh $TRAVIS_SCALA_VERSION; fi
  - if [ $KIND == tools ]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION scalajs-tools/package; fi
  - if [ $KIND == sbtplugin ]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION scalajs-tools/package scalajs-sbt-plugin/package scalajs-sbt-plugin/test; fi
  - if [ $KIND == partestc ]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION scalajs-partest/compile; fi
after_success:
  - if [[ "${PUBLISH_ENABLED}" == "true" && "${TRAVIS_PULL_REQUEST}" == "false" && "${KIND}" == "main" && "${PUBLISH_USER}" != "" && "${PUBLISH_PASS}" != "" ]]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION publish; fi
  - if [[ "${PUBLISH_COMPILER}" == "true" && "${TRAVIS_PULL_REQUEST}" == "false" && "${KIND}" == "main" && "${PUBLISH_USER}" != "" && "${PUBLISH_PASS}" != "" ]]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION scalajs-compiler/publish; fi
  - if [[ "${PUBLISH_ENABLED}" == "true" && "${TRAVIS_PULL_REQUEST}" == "false" && "${KIND}" == "sbtplugin" && "${PUBLISH_USER}" != "" && "${PUBLISH_PASS}" != "" ]]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION scalajs-tools/publish scalajs-sbt-plugin/publish; fi
  - if [[ "${PUBLISH_ENABLED}" == "true" && "${TRAVIS_PULL_REQUEST}" == "false" && "${KIND}" == "tools" && "${PUBLISH_USER}" != "" && "${PUBLISH_PASS}" != "" ]]; then sbt "${SBT_SETUP}" ++$TRAVIS_SCALA_VERSION scalajs-tools/publish; fi
env:
  global:
    - secure: "gIReAZ60hLtbYTlnNUM508LhhznImVPRO5fHQ/9SY7mqA/ql3EVJ65M43GxzvKjNkZ7thKj1ygYklCQaqXwdszR8xRRM7MNQIUImZhsjXJ0xqorpQf2fmo2sD54Gx/caAI4kx0x/ULm9ZA5QK6hprl8aVqb1o5bYAxfZdx719pE="
    - secure: "CiwH9VZ0Wl/fGsL6XUbXv92TWr+EnX94ICX2cbwwkvPDxmTrdWf8BZOq7JSrfITYvvW3l5U8YWLjCMpa/Cr2C2BD1QPvNXDoeL9cZXA0I2yquQNEfh12Zg5c5bHRtO+CeRHjq06jjEqojqTzp5MK10YXnfzzQFiZ1lt7c/rwmkU="
matrix:
  include:
    - jdk: openjdk6
      scala: 2.10.2
      env:
        - KIND=main
        - PUBLISH_COMPILER=true
    - jdk: openjdk6
      scala: 2.10.3
      env:
        - KIND=main
        - PUBLISH_COMPILER=true
    - jdk: openjdk6
      scala: 2.10.4
      env:
        - KIND=main
        - PUBLISH_ENABLED=true
    - jdk: openjdk6
      scala: 2.10.4
      env:
        - KIND=sbtplugin
        - PUBLISH_ENABLED=true
    - jdk: openjdk6
      scala: 2.11.0
      env:
        - KIND=main
        - PUBLISH_ENABLED=true
    - jdk: openjdk6
      scala: 2.11.0
      env:
        - KIND=tools
        - PUBLISH_ENABLED=true
    - jdk: openjdk6
      scala: 2.11.0
      env:
        - KIND=partestc
# This strangely fails on travis - #498
#    - jdk: oraclejdk7
#      scala: 2.10.2
#      env:
#        - KIND=main
    - jdk: oraclejdk7
      scala: 2.11.0
      env:
        - KIND=main
